### ISSUE TITLE
Implement Serializer::collect_str

### ISSUE THREAD

**Issue by dtolnay** [bincode-org/bincode#172]
https://docs.serde.rs/serde/ser/trait.Serializer.html#method.collect_str

Bincode should be able to do this without allocating a String.

**Comment by dgriffen** [comment]
I'm not sure there is a way to implement it within bincode more efficiently. bincode relies on having 8 byte length preceding the serialized string. The issue with that is the `write!` macro (and all others like it) will eventually end up calling [`write_fmt`](https://doc.rust-lang.org/std/io/trait.Write.html#method.write_fmt) twice for every `{}` field in a format string. Since it gets called multiple times and not all at once we have no way of determining the total length of the string. At least as far as I can tell.

**Comment by dtolnay** [comment]
That's fine, when serializing to a Vec\<u8\> it will need to go back and fill in the length after the fact. When serializing to an io::Write it can keep the current behavior.

**Comment by dgriffen** [comment]
Just to clarify, your suggestion is to use the default implementation when serializing to an `io::Write` and create a specialized implementation for serializing to a `Vec<u8>`?

**Comment by dtolnay** [comment]
Correct. We already do this for deserialization, where deserializing from \&[u8] vs io::Read follow different codepaths. That is what [`BincodeRead`](https://github.com/TyOverby/bincode/blob/1a277158270ebc194ac8812f7f4fe4bfa47b8b37/src/de/read.rs#L7) is for. It isn't `feature(specialization)` specialization but it relies on the caller going through `bincode::serialize` vs `bincode::serialize_into` as appropriate.

**Comment by dtolnay** [comment]
I am scheduling this for 1.0 because it affects the type signature of bincode::Serializer.

**Comment by TyOverby** [comment]
Ok yeah, I see how this can be done.

**Comment by TyOverby** [comment]
I'm moving this to post-1.0 because since the bincode::Serializer trait is no longer exported, there is not a backcompat issue.

**Comment by ZoeyR** [comment]
This actually affects the signature of `BincodeRead` if I'm understanding correctly. I think we're allowed to add a method if we provide a "default" implementation, which should be doable.
