### ISSUE TITLE
`skip_deserializing` variant attribute has confusing behavior

### ISSUE THREAD

**Issue by spikefoo** [bincode-org/bincode#184]
When using the `skip_deserializing` variant attribute, the derived deserializer doesn't match the derived serializer.

```rust
#[macro_use]
extern crate serde_derive;
extern crate bincode;

use bincode::{serialize, deserialize, Infinite};

#[derive(Debug, Serialize, Deserialize)]
enum Data {
    #[serde(skip_deserializing)]
    A,
    B,
    C,
}

fn main() {
    let data = Data::B;
    println!("data: {:?}", data);

    let encoded: Vec<u8> = serialize(&data, Infinite).unwrap();
    println!("encoded: {:?}", encoded);

    let decoded: Data = deserialize(&encoded[..]).unwrap();
    println!("decoded: {:?}", decoded);
}
```

output:

```
data: B
encoded: [1, 0, 0, 0]
decoded: C
```

The serializer serializes `A` to `0`, `B` to `1`, `C` to `2`. The deserializer deserializes `0` to `B` and `1` to `C`.

Note that adding `skip_serializing` doesn't change the output. It makes `A` illegal to serialize, but `B` is still serialized as `1`.

I'm not sure what the intended behavior of the `skip_serializing` and `skip_deserializing` variant attributes should be.

**Comment by oli-obk** [comment]
Jup, just checked: Serde's generated `Deserialize` impl doesn't match up with the `Serialize` impl.

It's a breaking change to change... But I'd consider this a serious bug, since it makes it impossible to use `skip_*` on types that both implement `Deserialize` and `Serialize`. Since it's unusable anyway, we won't be breaking anybody's code if we only change the behaviour on types that implement both `Deserialize` and `Serialize`. But if we change our generated `Deserialize` impl depending on whether a generated `Serialize` impl exists, it becomes a breaking change to add a generated `Serialize` impl to an enum already deriving `Deserialize`.

Not sure what the best course of action is, but I vote for simply fixing it and not create some weird behaviour depending on other impls.

**Comment by dtolnay** [comment]
Let's fix this so it reserves an index for skipped fields. So `{ #[serde(skip)] A, B, C }` would have B=1 and C=2 instead of B=0 and C=1.

**Comment by sdleffler** [comment]
This was a very odd bug to track down; in my code, it caused an error on deserialization along the lines of `bincode does not support Deserializer::deserialize`. I'm trying to use `#[serde(skip_serialization)]` and `#[serde(skip_deserialization)]` in tandem on an enum variant that should never be serialized or deserialized, but deserialization was erroring. Renaming the offending variant in such a way that its identifier, with respect to lexicographical order, comes *after* the only valid variant in the enum makes everything compile and round-trip just fine, which is for some reason highly entertaining to me.

**Comment by ZoeyR** [comment]
@dtolnay did this ever get fixed on the serde side?

**Comment by ZoeyR** [comment]
@dtolnay gentle ping on above

**Comment by little-dude** [comment]
Just tested with serde `v1.0.115` and it's still there
