### ISSUE TITLE
Size limiting when decoding is broken

### ISSUE THREAD

**Issue by joonazan** [bincode-org/bincode#299]
```rust
fn main() {
    let orig: Vec<u32> = vec![1, 2];
    let coded = bincode::config().limit(100).serialize(&orig).unwrap();
    println!("{:?}", coded);
    let res: Vec<u32> = bincode::config().limit(1).deserialize(&coded).unwrap();
}
```
The above program runs without errors.

Size limits seem to mostly work when encoding, but they fail to prevent the attacks they are meant to protect from.

It looks to me like the size of chars isn't counted either when decoding.

Maybe size limits should be removed? At least my use-case doesn't want a size limit.

If they are kept, the code should be refactored so that it is impossible to read bytes without advancing the size counter. That would be fairly easy especially if the dependency on `io::Read` in de/mod.rs is replaced with `BincodeRead`.

Based on https://github.com/servo/bincode/issues/206#issuecomment-335221752 it may be a good idea to avoid read_exact for performance anyway.

**Comment by joonazan** [comment]
I tried some more and was not able to get size limits to work even for strings where they are clearly implemented.

**Comment by ZoeyR** [comment]
Based on [this](https://github.com/servo/bincode/blob/16cde8489c2169e1951a1dd80b9db9938cc4c0be/src/internal.rs#L142) line I think this may be intentional. The limiter works with `deserialize_from`, just not `deserialize`. This is probably because `deserialize` works on slices which you must have fully loaded into memory anyways.
