### ISSUE TITLE
Custom discriminants values in enums

### ISSUE THREAD

**Issue by lemunozm** [bincode-org/bincode#393]
Hi!

I'm trying to serialize/deserialize a protocol specification. The protocol specifies the different message types with the first octet of the sequence, so I would want to represent it as an enum type, like this:

```rust
enum MyProtocol {
    Msg1(/* content */) // discriminator should be 4
    Msg2(/* content */) // discriminator should be 23
    Msg3(/* content */) // discriminator should be 42
}
```

How can I tell to `bincode` to write a specific discriminator for each enum variant in the serialized secuence?

Thanks!

**Comment by nmccarty** [comment]
Bincode uses the index provided by serde when serializing an enum. I checked serde, but was not able to find an attribute that allows modifying the index for an enum variant.

As this issue is currently out of scope for bincode, you can either file a feature request with serde, or handroll a serialize/deserialize implementation for your type.

**Comment by lemunozm** [comment]
Thanks for the answer!
