### ISSUE TITLE
Bincode panics on deserialize error

### ISSUE THREAD

**Issue by rkfox** [bincode-org/bincode#410]
When deserializing structs with Instant fields (serialized using serde_millis), bincode panics when there is a deserialization error instead of returning an Error.

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BincodeError(Custom("invalid system time"))', src/main.rs:14:53```

**Comment by VictorKoenders** [comment]
I'm guessing the panic happens because there's an `.unwrap()` in your `src/main.rs`, the panic probably doesn't happen in bincode itself.

The "invalid system time" seems to be an error of `serde_millis`. Specifically I found the message here: https://github.com/tailhook/serde-millis/blob/master/src/impls.rs#L33

Could you provide an example `main.rs` so we can check?

**Comment by rkfox** [comment]
I think you may be right about that. It isn't bincode that is panicing. Although bincode is having an issue deserializing Instants. The same documents encoded with serde_json load fine. I am having trouble reproducing the issue because it only happens with lots of documents.

**Comment by ghost** [comment]
Are you sure the issue is on deserialize? The `invalid system time` error looks to only be in the `Serialize` method of `SystemTime`

**Comment by ghost** [comment]
Also if you are serializing to a file make sure you `flush`

**Comment by rkfox** [comment]
I think you may be right that the issue comes from not using `flush` as I am serializing the data to a file and then deserializing from that file. It works with serde_json which might be a result of writing non-binary data that always ends with \n to the file. I will have to test later and close the issue.
