### ISSUE TITLE
Support for the Bytes type

### ISSUE THREAD

**Issue by andrenth** [bincode-org/bincode#453]
Hi

The `Bytes` type is quite prevalent in the Tokio ecosystem. It can be used with Bincode 1 because the `bytes` crate has a `serde` feature, but with Bincode 2’s departure from serde, that is not the case anymore.

Do you see Bincode 2 explicitly supporting `Bytes` encoding/decoding? Maybe under a feature flag?

**Comment by VictorKoenders** [comment]
Does the `serde` feature flag help you with this? There is some information here: https://docs.rs/bincode/2.0.0-alpha.1/bincode/serde/index.html

We're currently not sure how to do interop with other crates.

It would be ideal if other crates have a `bincode` feature that implements `Encode`/`Decode` on their types. 

Alternatively we could add a bunch of crate features to bincode (e.g. `uuid`, `bytes`, etc) but that list will be endless. It will also make your project break if e.g. `uuid` adds a bincode feature, and `bincode` has a uuid feature, because both will have `impl Encode/Decode for Uuid`.

**Comment by Stargateur** [comment]
As I run into the same problem I for now stay using serde macro, will see if some crates add bincode support, that say it would be nice to have a similar feature of serde [`with`](https://serde.rs/field-attrs.html#with) that allow flexibility for such problem.

I personally need at least `Bytes` and `chrono`

**Comment by ghost** [comment]
You can also add the `#[bincode(with_serde)]` attribute to fields that use serde in the `Encode` and `Decode` macros

**Comment by Stargateur** [comment]
> You can also add the `#[bincode(with_serde)]` attribute to fields that use serde in the `Encode` and `Decode` macros

that doesn't look documented or I miss it

**Comment by VictorKoenders** [comment]
https://docs.rs/bincode/2.0.0-beta.2/bincode/serde/index.html

> For interop with bincode’s derive feature, you can use the #[bincode(with_serde)] attribute on each field that implements serde’s traits.
