### ISSUE TITLE
Update documentation to explain why `config:;standard()` doesn't work with serde

### ISSUE THREAD

**Issue by Icelk** [bincode-org/bincode#506]
When I updated from beta-2 to beta-3, serialization and deserialization began to fail.
I get the error `SkipFixedArrayLengthNotSupported`.

See Icelk/agde#3 for the CI error. I'm not using any slices, just `Vec`.

This however works when serializing and deserializing using the standard methods and `bincode::serde::Compat`.

**Comment by VictorKoenders** [comment]
It turned out there was an issue with `serde` and not being able to encode fixed sized arrays. `bincode::config::standard()` sets `skip_fixed_array_length` by default. Because `serde` does not tell us that a fixed size array is being (de)serialized, and we simply get a slice, there was no way to detect this.

Because of this, we had to hard bail any `bincode::serde::*` function if `.skip_fixed_array_length` was set. If you use `bincode::config::standard().write_fixed_array_length()` it should all world.

**Comment by Icelk** [comment]
It now works as expected. Thanks for the swift reply and this library!

**Comment by VictorKoenders** [comment]
Gonna keep this open as a tracking issue to make the documentation more clear.

We should add a comment like my response on the following places:
- [EncodeError](https://docs.rs/bincode/2.0.0-beta.3/bincode/serde/enum.EncodeError.html) and [DecodeError](https://docs.rs/bincode/2.0.0-beta.3/bincode/serde/enum.DecodeError.html). This is probably (hopefully) the place people look first.
- [config::standard()](https://docs.rs/bincode/2.0.0-beta.3/bincode/config/fn.standard.html). as this is the place where people need to add `.write_fixed_array_length()`
- [config module](https://docs.rs/bincode/2.0.0-beta.3/bincode/config/index.html) as this is the place with the most explanation on `config`
- [Configuration.skip_fixed_array_length](https://docs.rs/bincode/2.0.0-beta.3/bincode/config/struct.Configuration.html#method.skip_fixed_array_length) already has it but [Configuration.write_fixed_array_length](https://docs.rs/bincode/2.0.0-beta.3/bincode/config/struct.Configuration.html#method.write_fixed_array_length) doesn't

**Comment by VictorKoenders** [comment]
We decided to make `.write_fixed_array_header` the default when using `config::standard()` so it would work better with `serde`

#509
