### ISSUE TITLE
async support for bincode2

### ISSUE THREAD

**Issue by yujqiao** [bincode-org/bincode#519]
Any plan for async support? Is it possible to have something like `encode_into_async_writer` and `decode_from_async_reader`?

**Comment by ghost** [comment]
We evaluated this in the past and in order to support both sync and async there would need to be two duplicate copies of almost the entire codebase. In my experience its far better to create a framing protocol for wire transfer in this case. Encode your type to a Vec, send the size of the Vec (in bytes) over your async writer, and then write the Vec. Do the opposite on the other side of the transmission.

**Comment by yujqiao** [comment]
>  In my experience its far better to create a framing protocol for wire transfer in this case

Better in terms of what? The simplicity of implementation?

One reason I hesitate to go in this way is the potential duplicated length information. Will this method waste traffic? Like the length can be inferred from bytes already received and actually not needed to deserialize the object correctly.

**Comment by VictorKoenders** [comment]
> Will this method waste traffic?

If you're sending the length of a message with every message as 4 bytes, you'll have a 4 byte overhead per message. If your application cannot afford sending 4 bytes per message extra; have you considered writing your own, highly specialized, project-specific encoding protocol? You could compress your messages by a lot more than just these 4 bytes.

**Comment by mkeeter** [comment]
I've also found the need for async `bincode`, but for a different reason, so I figure I'd share my use case.

I'm using `bincode` to serialize data structures which are, by volume, mostly large `bytes::Bytes` arrays.  I'm serializing these data structures in order to send them into a Tokio TCP socket, which is necessarily async.  Because the data is mostly byte arrays, the overhead from `memcpy` is extremely noticeable.  In https://github.com/oxidecomputer/crucible/pull/1183, I measure it at 11% of total runtime!

I think I need a function that looks like this:
```rust
pub async fn serialize_into_async<W, T: ?Sized>(writer: W, value: &T) -> Result<()>
where
    W: futures_io::AsyncWrite,
    T: serde::Serialize,
{
    // ...
```

If such a function existed, then I could serialize directly into the [`tokio::net::tcp::WriteHalf`](https://docs.rs/tokio/latest/tokio/net/tcp/struct.WriteHalf.html) (or, more realistically, a wrapper that buffers short writes but sends long writes directly down the wire).  This would be a dramatic performance improvement!

**Comment by dpc** [comment]
Yeap. I realize that it's an extra effort and duplicated  codepaths, etc. but async writer/reader support would be useful and can't be dismissed.
