### ISSUE TITLE
ErrorKind Clone

### ISSUE THREAD

**Issue by BR03D** [bincode-org/bincode#563]
Is there a reason for ErrorKind not implementing Clone? If not, can we make that happen?

**Comment by BR03D** [comment]
The new DecodeError does not implement it either - why?

**Comment by VictorKoenders** [comment]
I'm assuming you mean `EncodeError`. This enum uses the following types that do not implement `Clone`:
- [core::cell::BorrowError](https://doc.rust-lang.org/stable/core/cell/struct.BorrowError.html)
- [std::io::Error](https://doc.rust-lang.org/stable/std/io/struct.Error.html)

We could implement `Clone` on `DecodeError` but I think it makes sense that both error types implement the same traits

**Comment by BR03D** [comment]
I was specifically referring to DecodeError. My application reads input from a TcpStream and in case of a DecodeError I want to attach that error to the return value (which i would like to be cloneable).

I dont see why both errors need to implement the same traits - imo if something can be Clone it should be.

**Comment by VictorKoenders** [comment]
You could wrap the `DecodeError` in an `Arc` or `Rc`, that would give you a `Clone` implementation

**Comment by BR03D** [comment]
That is a good suggestion. I will implement it like this for now.

Still, if there is no reason for why it wouldnt be `Clone`, it should probably implement it.

**Comment by VictorKoenders** [comment]
Turns out `DecodeError` should import `std::io::Error`, so I've added that in [this PR](https://github.com/bincode-org/bincode/pull/574).

If you want the two types mentioned above to implement `Clone`, please open up an issue on the [rust issue tracker](https://github.com/rust-lang/rust/issues). We are open to implement any trait that `core::cell::BorrowError` and `std::io::Error` implement.

Feel free to re-open this issue when the traits implements change in a stable version of rust.
