### ISSUE TITLE
enum encoding

### ISSUE THREAD

**Issue by lazyclaw-labs** [bincode-org/bincode#566]
I am new to bincode, I got a simple scenario to serialize/desrialize an enum, which has string in it. i.e.:
pub enum E
{
     STRING(String),
     INT(i32)
}

After serialization, I found two things I am not happy:
1. enum order number is a i32, used up 4 bytes. 1 byte should be enough.
2. String length, use i64, i32 should be enough.

So is there anyway to configre bincode to serialize/deserialize using above 2 specs? i.e., the layout should look like:

0 x x x x Action String followed length (x x x x), 0 is the order
1 x x x x (this is i32), 1 is the order

**Comment by nmccarty** [comment]
Bincode not using a u8 for enum discriminators is an [intentional design descision](https://github.com/bincode-org/bincode#why-does-bincode-not-respect-repru8) (see #565 for related ongoing discussion).

If you wish to save some space, you can use the varint encoding, see the following for documentation:
- [The options documentation](https://docs.rs/bincode/latest/bincode/config/trait.Options.html) for bincode 1.x
- [The configuration documentation](https://docs.rs/bincode/2.0.0-rc.1/bincode/config/struct.Configuration.html) for bincode 2.0.0-rc.1 

Bincode is designed to be a stable, simple, and lightweight format, and is not intended to minimize bytes written or provide low-level control over the output format, however, if you must, you can manually implement the [`Encode`](https://docs.rs/bincode/2.0.0-rc.1/bincode/enc/trait.Encode.html#implementing-this-trait-manually) and [`Decode`](https://docs.rs/bincode/2.0.0-rc.1/bincode/de/trait.Decode.html#implementing-this-trait-manually) for your type to control output format.

**Comment by bitdivine** [comment]
@szguoxz - I have similar requirements.  I have made [a branch with u8 enum fields](https://github.com/bitdivine/bincode_u8_enum).  Something similar could doubtless be done with the length field.

Note that I have made the branch purely with my own use in mind; if there are more users, it would make sense to make the change in a slightly different way.  (Add a field for the encoding config, keep the error `found` field as u32, change only the encoding and decoding type in derive/src/derive_enum.rs)  The maintainers, very understandably, do not want to support the additional complexity of such a variation.  Also, given that the encoding config is applied at runtime, not at compile time, every additional configuration flag is going to slow down the codec.
