### ISSUE TITLE
Manual Decode implementation causes 2.0.0-rc2 to complain about missing BorrowDecode implementation

### ISSUE THREAD

**Issue by reinhardbluelab** [bincode-org/bincode#589]
Hi,

I'm getting the following error since updating from 2.0.0-rc1 to rc2:  _the trait `BorrowDecode<'_>` is not implemented for `X`_, where enum `X` has a manual implementation of the `Decode` trait. Is this intended behavior?

Enum `X` doesn't have any borrowed data; it's a simple enum where the variants have no associated data. It is used in another struct that uses the derived `Decode` trait.

Everything worked fine in 2.0.0-rc1, i.e. I did not need to implement the `BorrowDecode` trait as well. From the bincode documentation it seems like I need to implement either the  `Decode` or `BorrowDecode` trait (not both) if I need custom decoding behavior.

Am I missing something?

**Comment by VictorKoenders** [comment]
We had a breaking change between -rc.1 and -rc.2. You have to implement `BorrowDecode` and `Decode` explicitly now, before this was auto-implemented.

If your implementation does not have generics, you can auto-implement `BorrowDecode` with the [`bincode::impl_borrow_decode`](https://docs.rs/bincode/2.0.0-rc.2/bincode/macro.impl_borrow_decode.html) macro. Otherwise you'll have to implement it manually.

The example at [`bincode::de::Decode`](https://docs.rs/bincode/2.0.0-rc.2/bincode/de/trait.Decode.html) has also been updated

**Comment by VictorKoenders** [comment]
Note that you should only need `BorrowDecode` for [`borrow_decode_from_slice`](https://docs.rs/bincode/2.0.0-rc.2/bincode/fn.borrow_decode_from_slice.html).

All the `decode_from_*` methods should work with types that only implement `Decode`

**Comment by reinhardbluelab** [comment]
The top-level struct just derives `Decode` and I don't use `borrow_decode_from_slice` anywhere, but I still needed to use `bincode::impl_borrow_decode` (as suggested) to fix the errors. Thanks for your help.

**Comment by reinhardbluelab** [comment]
Is `BorrowDecode` auto-implemented when I derive `Decode` for a struct? I guess that would explain why I need to manually implement `BorrowDecode` now too for one of the contained fields (even though I don't use `borrow-decode_*` anywhere). 

Thanks for all you hard work with this crate!

**Comment by VictorKoenders** [comment]
> Is BorrowDecode auto-implemented when I derive Decode for a struct?

Yes, `BorrowDecode` should be automatically implemented when you auto-derive `Decode`
