### ISSUE TITLE
Why was `PartialEq` derive removed from `DecodeError`?

### ISSUE THREAD

**Issue by reinhardbluelab** [bincode-org/bincode#590]
I had a unit test that compared the returned value of `bincode::decode_from_slice` (using `assert_eq!`), but since derive `PartialEq` was removed from `DecodeError` in 2.0.0-rc2 this causes an error: _Binary operation `==` cannot be applied to type_. 

Shouldn't `DecodeError` derive the `PartialEq` or `Eq` trait so that `DecodeError` instances can be compared?

**Comment by VictorKoenders** [comment]
rc-1 was incorrectly dropping underlying [`std::io::Error`](https://doc.rust-lang.org/stable/std/io/struct.Error.html)s, so those had to be added to the `DecodeError` as variants (https://github.com/bincode-org/bincode/pull/574). Because `std::io::Error` does not implement `PartialEq` or `Eq` we cannot auto-derive it ourselves.

I personally think that `std::io::Error` should implement more traits (`Eq`, `PartialEq`, `Clone`, etc) but this should be taken up with the rust-lang devs

**Comment by reinhardbluelab** [comment]
Thanks for the explanation. Interestingly, I see that that `std::io::ErrorKind` derives some of those traits.
