### ISSUE TITLE
Feature: support for heapless crate

### ISSUE THREAD

**Issue by LuckyTurtleDev** [bincode-org/bincode#643]
It would be nice if bincode 2 would have support to encode and decode the [heapless](https://crates.io/crates/heapless) crate. This would allow using vectors at no_std and no_alloc environment.

Currently I convert the vector to an array of option, to be send via bincode.

**Comment by VictorKoenders** [comment]
Ideally we would want to have other crates implement bincode, instead of bincode implementing all of the crates in the rust ecosystem.

Have you tried using `#[bincode(with_serde)]` as described [here](https://docs.rs/bincode/2.0.0-rc/bincode/migration_guide/index.html#bincode-derive-and-libraries)? I wonder if that will give an ergonomic-enough API for you to work with.

We'll run into issues when we finally release bincode 2.0 and other crates are thinking of implementing bincode in their crate, but bincode also provides an implementation.
