### ISSUE TITLE
Support for the "bytes" crate

### ISSUE THREAD

**Issue by aegroto** [bincode-org/bincode#650]
Referring to bincode v2, I can see that Encode and Decode are not implemented for [bytes](https://docs.rs/bytes/latest/bytes/) types. Is it intentional or is there a chance to add implementations for those types? I am willing to contribute if this is something that could be of interest for the community.

**Comment by VictorKoenders** [comment]
Ideally we would want to have other crates implement bincode, instead of bincode implementing all of the crates in the rust ecosystem.

Have you tried using `#[bincode(with_serde)]` as described [here](https://docs.rs/bincode/2.0.0-rc/bincode/migration_guide/index.html#bincode-derive-and-libraries)? I wonder if that will give an ergonomic-enough API for you to work with.

We'll run into issues when we finally release bincode 2.0 and other crates are thinking of implementing bincode in their crate, but bincode also provides an implementation.

**Comment by aegroto** [comment]
Hello, sorry for the late reply. Thanks for your suggestion, I have not tried to encode bytes objects by relying on serde, but I will port my code to do so and let you know as soon as possible.

**Comment by aegroto** [comment]
Sorry for the lack of updates, I didn't have any time to test out the proposed solution yet. Is there any ETA for bincode v2?

**Comment by VictorKoenders** [comment]
There is no ETA for bincode v2, all the maintainers have been very busy with non-OSS things this year

**Comment by aegroto** [comment]
Thanks for your response @VictorKoenders. Is there any checklist of what's missing and priorities for the release? If so, I will to have a look at that.

**Comment by VictorKoenders** [comment]
Basically all issues that are labeled with `bincode-2`

**Comment by aegroto** [comment]
Thanks, I will give a look at it as soon as I can.
